cask_args appdir: "/Applications"

tap "caskroom/cask"

cask "atom"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "java"
cask "jdownloader"
cask "karabiner"
cask "transmission"
cask "virtualbox"
cask "vlc"

cask "vagrant"

brew "ack"
brew "awscli"
brew "bash-completion"
brew "bash-git-prompt"
brew "brew-cask"
brew "cabal-install"
brew "coreutils"
brew "emacs"
brew "ghc"
brew "git"
brew "go"
brew "gradle"
brew "haskell-stack"
brew "hugo"
brew "htop-osx"
brew "jq"
brew "leiningen"
brew "maven"
brew "n"
brew "openssl"
brew "p7zip"
brew "reattach-to-user-namespace"
brew "ruby-build"
brew "rbenv"
brew "unrar"
brew "sbt"
brew "scala"
brew "thefuck"
brew "tree"
brew "tmux"
brew "typesafe-activator"
brew "terraform"
brew "unrar"
brew "weechat"
brew "wget"