#!/usr/bin/env ruby

require 'fileutils'
require 'optparse'

# map of command line options
options = {}

options[:onlylinks] = false

# array of files/folders to symlink
files = %w{
  .bash_profile
  .gitconfig
  .gitignore_global
  .tmux.conf
  .tmuxinator
}

# parse command line options
OptionParser.new do |opts|
  opts.on("-p [ARG]", "--platform [ARG]") do |p|
    options[:platform] = p
  end

  opts.on("-l", "--links-only") do |p|
    options[:onlylinks] = true
  end
end.parse!

# symlink files/folders
files.each do |f|
  if File.exist?("#{ENV['HOME']}/#{f}")
    puts "File #{f} already exists in home folder, SKIPPING"
  else
    File.symlink("#{File.expand_path(File.dirname(__FILE__))}/#{f}", "#{ENV['HOME']}/#{f}")
  end
end