GIT_CONFIG=ubuntu/.gitconfig

# array files to symlink into home dir
refs = ubuntu/.bash_profile \
	   .gitignore_global \
	   ubuntu/.tmux.conf \
	   .emacs.d

# ORDERED array of scripts to run
scripts = ubuntu/add-repos.sh \
		  ubuntu/scripts/install.sh \
		  scripts/rust.sh