GIT_CONFIG=arch/.gitconfig

# array files to symlink into home dir
refs = arch/.bash_profile \
	   .gitignore_global \
	   arch/.tmux.conf \
	   .emacs.d

# ORDERED array of scripts to run
scripts = arch/scripts/install-packages.sh \
		  arch/scripts/docker.sh \
		  scripts/node.sh \
		  scripts/rust.sh