SCRIPTS_PATH=${PWD}/arch/scripts

# array files to symlink into home dir
refs = .profile \
	   arch/.bash_profile \
	   .gitconfig \
	   .gitignore_global \
	   arch/.tmux.conf \
	   .emacs.d

# ORDERED array of scripts to run
scripts = arch/scripts/install-packages.sh \
		  arch/scripts/docker.sh \
		  arch/scripts/java.sh \
		  scripts/bash.sh \
		  scripts/rust.sh