GIT_CONFIG=fedora/.gitconfig

# array files to symlink into home dir
refs = fedora/.bash_profile \
	   .gitignore_global \
	   fedora/.tmux.conf \
	   .emacs.d

# ORDERED array of scripts to run
scripts = fedora/scripts/add-repos.sh \
		  fedora/scripts/install.sh \
		  scripts/rust.sh
