# array files to symlink into home dir
refs = .bash_profile \
	   .gitconfig \
	   .gitignore_global \
	   .tmux.conf \
	   .emacs.d

# ORDERED array of scripts to run
scripts = osx/scripts/homebrew.sh \
		  scripts/bash.sh