# array files to symlink into home dir
refs = .profile \
	   .bash_profile \
	   .gitconfig \
	   .gitignore_global \
	   .tmux.conf \
	   .emacs.d

# ORDERED array of scripts to run
scripts = osx/scripts/install-packages.sh \
		  osx/scripts/docker.sh \
		  osx/scripts/java.sh \
		  scripts/bash.sh \
		  scripts/rust.sh